name: Build efs-utils

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev
        sudo apt-get -y install git binutils rustc cargo pkg-config libssl-dev gettext

    - name: Build DEB package
      run: |
        ls -al
        # ./build-deb.sh

    # - name: Upload artifacts
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: efs-utils-package
    #     path: build/amazon-efs-utils*.deb
