name: Build efs-utils

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install git binutils rustc cargo pkg-config libssl-dev gettext

    - name: Build DEB package
      run: |
        ./build-deb.sh

    - name: Get package name
      id: get_package_name
      run: |
        cd build
        echo "PACKAGE_NAME=$(ls -1 amazon-efs-utils*.deb | head -1 | tr -d '\n')" >> $GITHUB_OUTPUT
  
    - name: Publish package
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.get_package_name.outputs.PACKAGE_NAME }}
        path: build/amazon-efs-utils*.deb

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ steps.get_package_name.outputs.PACKAGE_NAME }}
        files: build/amazon-efs-utils*.deb
        fail_on_unmatched_files: true
        make_latest: true
