name: Build efs-utils

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version to build, based on tags. For example, v1.0.0."
        required: true

jobs:
  build:
    strategy:
      matrix:
        ubuntu-version: ["22", "24"]

    runs-on: ubuntu-${{ matrix.ubuntu-version }}.04



    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.version }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install git binutils rustc cargo pkg-config libssl-dev gettext

    - name: Build DEB package
      run: |
        ./build-deb.sh

    - name: Get package name
      id: get_package_name
      run: |
        cd build
        echo "PACKAGE_NAME=$(ls -1 amazon-efs-utils*.deb | head -1 | tr -d '\n')" >> $GITHUB_OUTPUT

    - name: Rename package
      run: |
        mv build/amazon-efs-utils*.deb build/ubuntu-${{ matrix.ubuntu-version }}.04-${{ steps.get_package_name.outputs.PACKAGE_NAME }}

    - name: Publish package
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu-${{ matrix.ubuntu-version }}.04-${{ steps.get_package_name.outputs.PACKAGE_NAME }}
        path: build/ubuntu*.deb

  release:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        pattern: '*.deb'
        merge-multiple: true

    - name: Verify artifacts
      run: |
        ls -lR

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ inputs.version }}
        files: '*.deb'
        fail_on_unmatched_files: true
        make_latest: false
